sudo: false
language: ruby
rvm:
  - 2.4.1
  - jruby-9.1.10.0

  # older versions
  - 2.3.4
  - 2.2.7
  - 2.1.9
  - 2.0.0
  - 1.9.3

  - jruby-9.0.5.0
  - jruby-1.7.27

  - ruby-head
  - jruby-head

  - rbx

script: bundle exec rake && RAMDA_DEBUG=true bundle exec rake

matrix:
  include:
    - rvm: 2.3.4
      jdk: oraclejdk8
      env: COVERAGE=1

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    # FIXME
    - rvm: jruby-1.7.27
    - rvm: rbx

before_install: gem install bundler -v 1.15.1
