app:
  container_name: rambda_ruby_app
  build: .
  dockerfile: Dockerfile
  volumes:
    - .:/srv/app
    - ./config/config.yml.example:/srv/app/config/config.yml
    - ~/.gem/credentials:/root/.gem/credentials
    - ~/.gitconfig:/root/.gitconfig
  volumes_from:
    - bundle_cache

bundle_cache:
  container_name: rambda_ruby_bundle_cache
  image: busybox
  volumes:
    - /bundle_cache
